/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Erni
 */
public class MenuPrincipal extends javax.swing.JFrame {


    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        String rutaImagen = "D:\\NetBeans\\ComprasGrupo14\\build\\Data\\fondo.jpg";
        ImageIcon fondo = new ImageIcon(rutaImagen);
        JLabel label = new JLabel(fondo);
        label.setBounds(0, 0, fondo.getIconWidth(), fondo.getIconHeight());
        jdEscritorio.add(label, new Integer(Integer.MIN_VALUE));
  
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbCompras = new javax.swing.JButton();
        jbProveedores = new javax.swing.JButton();
        jbProducto = new javax.swing.JButton();
        jbDetalle = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jdEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jbCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/System/Qr_Code.png"))); // NOI18N
        jbCompras.setText("Compras");
        jbCompras.setFocusable(false);
        jbCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprasActionPerformed(evt);
            }
        });
        jToolBar1.add(jbCompras);

        jbProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/System/Data.png"))); // NOI18N
        jbProveedores.setText("Proveedores");
        jbProveedores.setFocusable(false);
        jbProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbProveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbProveedores);

        jbProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/System/Mouse.png"))); // NOI18N
        jbProducto.setText("Producto");
        jbProducto.setFocusable(false);
        jbProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductoActionPerformed(evt);
            }
        });
        jToolBar1.add(jbProducto);

        jbDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/System/Bar_Bottom.png"))); // NOI18N
        jbDetalle.setText("Detalle compra");
        jbDetalle.setFocusable(false);
        jbDetalle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbDetalle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbDetalle);

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos archivos/File/Folders.png"))); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.setFocusable(false);
        jbSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSalirMouseClicked(evt);
            }
        });
        jToolBar1.add(jbSalir);

        javax.swing.GroupLayout jdEscritorioLayout = new javax.swing.GroupLayout(jdEscritorio);
        jdEscritorio.setLayout(jdEscritorioLayout);
        jdEscritorioLayout.setHorizontalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jdEscritorioLayout.setVerticalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(jdEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdEscritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbComprasActionPerformed

    private void jbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductoActionPerformed

jdEscritorio.removeAll();
jdEscritorio.repaint();
ProductoVista pv = new ProductoVista();
pv.setVisible(true);
jdEscritorio.add(pv);
jdEscritorio.moveToFront(pv);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbProductoActionPerformed

    private void jbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSalirMouseClicked
        dispose();
    }//GEN-LAST:event_jbSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            MenuPrincipal frame = new MenuPrincipal();
            frame.setLocationRelativeTo(null); // Centrar la ventana en la pantalla
            frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbCompras;
    private javax.swing.JButton jbDetalle;
    private javax.swing.JButton jbProducto;
    private javax.swing.JButton jbProveedores;
    private javax.swing.JButton jbSalir;
    private javax.swing.JDesktopPane jdEscritorio;
    // End of variables declaration//GEN-END:variables
}
